Fatal error: Uncaught exception 'Exception' with message 'Return exception handle' in %s:6
Stack trace:
#0 %s(14): Hack\UserDocumentation\Async\Exceptions\Examples\MultipleAwaitable\exception_thrower()
#1 %s(21): Hack\UserDocumentation\Async\Exceptions\Examples\MultipleAwaitable\multiple_waithandle_exception()
#2 {main}
